# Generated by Django 5.1.4 on 2024-12-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='icon',
        ),
        migrations.AddField(
            model_name='theme',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
