# Generated by Django 5.1.4 on 2024-12-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_theme_icon_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
