# Generated by Django 5.1.4 on 2025-01-05 22:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_favorite_delete_userprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'theme')},
        ),
    ]
