# Generated by Django 5.1.4 on 2025-01-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='theme_images/'),
        ),
    ]
