# Generated by Django 5.1.4 on 2025-01-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_theme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='accept_close_answer',
            field=models.BooleanField(default=False),
        ),
    ]
