# Generated by Django 5.1.4 on 2025-01-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quiz_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='question',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Texte'), ('IMG', 'Image')], max_length=20),
        ),
        migrations.CreateModel(
            name='EnumQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('valid', models.BooleanField(default=False)),
                ('difficulty', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enum_questions', to='quiz.theme')),
            ],
        ),
        migrations.CreateModel(
            name='EnumAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=255)),
                ('enum_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enum_answers', to='quiz.enumquestion')),
            ],
        ),
    ]
