# Generated by Django 5.1.4 on 2025-01-20 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_question_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enumanswer',
            name='enum_question',
        ),
        migrations.CreateModel(
            name='EnumQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('valid', models.BooleanField(default=False)),
                ('difficulty', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enum_quizzes', to='quiz.theme')),
            ],
        ),
        migrations.AddField(
            model_name='enumanswer',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enum_answers',
                                    to='quiz.enumquiz'),
        ),
        migrations.DeleteModel(
            name='EnumQuestion',
        ),
    ]
