# Generated by Django 5.1.4 on 2025-01-21 12:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_enumanswer_enum_question_enumquiz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='ClassicQuiz',
        ),
    ]
