# Generated by Django 5.1.4 on 2025-01-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_rename_quiz_classicquiz'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizQuestion',
            new_name='ClassicQuizQuestion',
        ),
    ]
