# Generated by Django 5.1.4 on 2025-01-21 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_rename_quizquestion_classicquizquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classicquiz',
            name='is_temporary_quiz',
        ),
        migrations.AddField(
            model_name='classicquiz',
            name='difficulty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='classicquiz',
            name='type',
            field=models.CharField(choices=[('CL', 'Classic'), ('RA', 'Random'), ('EN', 'Enumeration'), ('MT', 'Match')], default='CL', max_length=2),
        ),
        migrations.AddField(
            model_name='classicquiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='classicquiz',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classicquiz',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classicquiz',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
