# Generated by Django 5.1.4 on 2025-01-21 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_remove_classicquiz_is_temporary_quiz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enumanswer',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='enumquiz',
            name='theme',
        ),
        migrations.AddField(
            model_name='enumanswer',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enumquiz',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enum_quizzes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enumquiz',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='enum_quizzes', to='quiz.theme'),
        ),
        migrations.AddField(
            model_name='enumquiz',
            name='title',
            field=models.CharField(default='titre', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enumquiz',
            name='type',
            field=models.CharField(choices=[('CL', 'Classic'), ('RA', 'Random'), ('EN', 'Enumeration'), ('MT', 'Match')], default='CL', max_length=2),
        ),
        migrations.AddField(
            model_name='enumquiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classicquiz',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classic_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classicquiz',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='classic_quizzes', to='quiz.theme'),
        ),
        migrations.AlterField(
            model_name='enumquiz',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
