# Generated by Django 5.1.4 on 2025-01-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_enumanswer_options_remove_enumquiz_theme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classicquizquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='classicquizquestion',
            name='questions',
            field=models.ManyToManyField(related_name='classic_quizzes', to='quiz.question'),
        ),
    ]
