# Generated by Django 5.1.4 on 2025-01-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_remove_classicquizquestion_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicquiz',
            name='questions',
            field=models.ManyToManyField(related_name='classic_quizzes', to='quiz.question'),
        ),
        migrations.DeleteModel(
            name='ClassicQuizQuestion',
        ),
    ]
