# Generated by Django 5.1.4 on 2025-01-24 12:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_classicquiz_questions_delete_classicquizquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='enumanswer',
            old_name='answer_text',
            new_name='answer_text_en',
        ),
        migrations.AddField(
            model_name='enumanswer',
            name='answer_text_fr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TEXT', 'Texte'), ('IMG', 'Image'), ('MTCH', 'Match')], max_length=20),
        ),
        migrations.CreateModel(
            name='MatchQuiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CL', 'Classic'), ('RA', 'Random'), ('EN', 'Enumeration'), ('MT', 'Match')], default='CL', max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.FloatField(default=0.0)),
                ('valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_quizzes', to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(blank=True, related_name='match_quizzes', to='quiz.question')),
                ('themes', models.ManyToManyField(blank=True, related_name='match_quizzes', to='quiz.theme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_clue', models.TextField(blank=True, null=True)),
                ('picture_clue', models.URLField(blank=True, null=True)),
                ('answer', models.CharField(max_length=255)),
                ('match_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='quiz.matchquiz')),
            ],
        ),
    ]
