# Generated by Django 5.1.4 on 2025-01-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_rename_answer_text_enumanswer_answer_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchquiz',
            name='text',
            field=models.TextField(default='Test'),
            preserve_default=False,
        ),
    ]
