# Generated by Django 5.1.4 on 2025-01-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_matchquiz_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpair',
            name='text_clue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
