# Generated by Django 5.1.4 on 2025-01-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_alter_matchpair_text_clue'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchquiz',
            name='base_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
