# Generated by Django 5.1.4 on 2025-01-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_matchquiz_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpair',
            name='picture_clue',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
