# Generated by Django 5.1.4 on 2025-01-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_alter_matchpair_picture_clue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpair',
            name='picture_clue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
