# Generated by Django 5.1.4 on 2025-01-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_alter_matchpair_picture_clue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TXT', 'Texte'), ('IMG', 'Image'), ('CHO', 'Choices')], max_length=20),
        ),
    ]
