# Generated by Django 5.2.6 on 2025-09-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('quiz', '0024_alter_question_question_type'),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='theme',
        ),
        migrations.DeleteModel(
            name='Synonym',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='parent_theme',
        ),
        migrations.AlterField(
            model_name='classicquiz',
            name='questions',
            field=models.ManyToManyField(related_name='classic_quizzes', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='classicquiz',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='classic_quizzes', to='themes.theme'),
        ),
        migrations.AlterField(
            model_name='enumquiz',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='enum_quizzes', to='themes.theme'),
        ),
        migrations.AlterField(
            model_name='matchquiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='match_quizzes', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='matchquiz',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='match_quizzes', to='themes.theme'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
