# Generated by Django 5.2.6 on 2025-09-24 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym_text', models.TextField()),
                ('reference_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('TXT', 'Texte'), ('IMG', 'Image'), ('CHO', 'Choices')], max_length=20)),
                ('question_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Image')),
                ('correct_answer', models.CharField(max_length=255)),
                ('accept_close_answer', models.BooleanField(default=False)),
                ('difficulty', models.FloatField(default=0.0)),
                ('valid', models.BooleanField(default=False)),
                ('fake_answer_1', models.CharField(blank=True, max_length=255, null=True)),
                ('fake_answer_2', models.CharField(blank=True, max_length=255, null=True)),
                ('fake_answer_3', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='themes.theme')),
            ],
        ),
    ]
